import {
    Smartphone,
    Code,
    Database,
    Globe,
    Server,
    Layout,
    Activity,
    CreditCard,
    MessageSquare,
    Zap,
    Cloud,
    Lock,
    Cpu,
    Layers,
    Package,
    Terminal,
    GitBranch,
    FileCode,
    Palette,
    Boxes,
    Workflow,
    Binary,
    Braces,
    Bug,
    Flame,
    Sparkles,
    Rocket,
    type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
    Smartphone,
    Code,
    Database,
    Globe,
    Server,
    Layout,
    Activity,
    CreditCard,
    MessageSquare,
    Zap,
    Cloud,
    Lock,
    Cpu,
    Layers,
    Package,
    Terminal,
    GitBranch,
    FileCode,
    Palette,
    Boxes,
    Workflow,
    Binary,
    Braces,
    Bug,
    Flame,
    Sparkles,
    Rocket,
};

export const getIconComponent = (iconName: string): LucideIcon | null => {
    return iconMap[iconName] || null;
};

export const iconNames = Object.keys(iconMap).sort();
